$('.head th.w').html('w');
$('.head th.pi').html('pi');
$('.head th.d0').html('M');
$('.head th.d1').html('T');
$('.head th.d2').html('W');
$('.head th.d3').html('Th');
$('.head th.d4').html('F');
$('.head th.d5').html('Sa');
$('.head th.d6').html('Su');
